### ISSUE TITLE
simple config to run transformer

### ISSUE THREAD

**Issue by songtaoshi** [dsindex/etagger#1]
hello Myungchu, thanks your code for experiments of ner. Could you show a simple and explicit step to use the transformer to train.

**Comment by dsindex** [comment]
@songtaoshi 

for convenience, you can checkout :
https://github.com/dsindex/etagger/releases/tag/v.0.12

```
$ git clone https://github.com/dsindex/etagger.git --branch=v.0.12
```

1. pre-requisites
https://github.com/dsindex/etagger#pre-requisites

2. transformer setting
set learning_rate to '0.0003' in config.py and __tf_used to 'True' in model.py.

3. build word embedding and vocabularies to pickle
```
$ python embvec.py --emb_path embeddings/glove.840B.300d.txt --wrd_dim 300 --train_path data/train.txt --total_path data/total.txt --lowercase 0 --elmo_vocab_path embeddings/elmo_vocab.txt --elmo_options_path embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json --elmo_weight_path embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
```

4. train
```
$ python train.py --emb_path embeddings/glove.840B.300d.txt.pkl --wrd_dim 300 --batch_size 20 --epoch 70
```

5. inference and evaluation
```
$ python inference.py --mode bucket --emb_path embeddings/glove.840B.300d.txt.pkl --wrd_dim 300 --restore checkpoint/ner_model < data/test.txt > pred.txt
$ python token_eval.py < pred.txt
$ python chunk_eval.py < pred.txt
```
