### ISSUE TITLE
Some confusion about the repository.

### ISSUE THREAD

**Issue by sbmaruf** [dsindex/etagger#2]
Hi there. Awesome repository. Thank you for making it public.
In your README.md file you reported BERT is giving you around 92.44% where as in the BERT paper they said without CRF layer they even got `92.8`  and they didn't even used any encoder.. And you are also using lot of other good feature, like `POS` tags. Can you give a comment on that?
Another thing, in your code you commented out [`[SEP]` tag](https://github.com/dsindex/etagger/blob/master/input.py#L166).  Why did you do that? What I am confused if if `[PAD]` should be before or after `[SEP]` tag.

**Comment by dsindex** [comment]
1. 
92.44% on average was obtained by ‘elmo+glove’ not by ‘bert’. (see experiments 10, test 15 in README_DEV.md)
you can refer the f-score in case bert used only.
```
in README_DEV.md
experiments 11, test 5
....
# BERT only(no glove, no cnn, no lstm, no crf)
token : 0.9275558564658091
chunk : 0.9169470515317868 -> BERT large + Softmax best
```

even though i used a lot of features with bert embedding,  i was not able to reproduce the result of the paper(92.8%).
max f-score was 91.88%

2. 
at first, i used the ‘SEP’ token. but after i read the paper carefully, i found there is no ‘SEP’ in the picture of the use case of NER.so i commented out. it also works fine.

**Comment by sbmaruf** [comment]
@dsindex  ahh. Now I see in figure 3. You are right.Thanks for the reply.
