### ISSUE TITLE
Performance issues in etagger/blob/master/input.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [dsindex/etagger#5]
Hello,I found a performance issue in the definition of `__dataset_input_fn` ,
dsindex/etagger/blob/master/input.py,
[dataset = dataset.map(parser)](https://github.com/dsindex/etagger/blob/1148beaef9d614117aee45e6e82ac02d7eb9d094/input.py#L141) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by dsindex** [comment]
thank you so much!
you can freely create PR~
